# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Button, PhotoImage, Frame, Label

import commands as cmnd

dt = cmnd.deftheme

window = Tk()

window.geometry("700x390")
window.configure(bg = dt.bg_light)


canvas = Canvas(
    window,
    bg = dt.bg_light,
    height = 390,
    width = 700,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

kick_image = PhotoImage(
    file=cmnd.relative_to_assets("kick.png"))
lead_image = PhotoImage(
    file=cmnd.relative_to_assets("lead.png"))

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    550.0,
    0.0,
    700.0,
    390.0,
    fill=dt.bg_medium,
    outline="")

friend = Button(
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
friend.place(
    x=560.0,
    y=10.0,
    width=130.0,
    height=40.0
)

canvas.create_text(
    605.0,
    21.0,
    anchor="nw",
    text="FriendName",
    fill=dt.fg,
    font=("Inter SemiBold", 12 * -1)
)

friend_image = PhotoImage(
    file=cmnd.relative_to_assets("test.png"))
friendIcon = canvas.create_image(
    580.0,
    30.0,
    #image=window.images["friend"]
)

#member backgrounds for empty spaces
for i in range(0, 4):
    canvas.create_rectangle(
        310.0,
        ((i+1)*10)+(i*85),
        540.0,
        ((i+1)*10)+(i*85)+85,
        fill=dt.bg_medium,
        outline="")

member1 = Frame(
    window,
    width=230,
    height=85, 
    bg=dt.bg_medium
)
member1.place(x=310, y=10)

member1.images = {"kick": kick_image, "lead": lead_image}

gr1kick = Button(
    member1,
    image=member1.images["kick"],
    borderwidth=0,
    highlightthickness=0,
    relief="flat",
    bg=dt.bg_medium,
    activebackground=dt.bg_medium, 
    name="kick"
)
gr1kick.image = member1.images["kick"]
gr1kick.place(x=189, y=45, width=30, height=30)

gr1lead = Button(
    member1,
    image=member1.images["lead"],
    borderwidth=0,
    highlightthickness=0,
    relief="flat",
    bg=dt.bg_medium,
    activebackground=dt.bg_medium, 
    name="promote"
)
gr1lead.place(x=153, y=45, width=30, height=30)

g1primrole = Label(member1, bg=dt.bg_medium, name="prim_icon")
g1primrole.place(x=81, y=45, width=30, height=30)

g1secrole = Label(member1, bg=dt.bg_medium, name="sec_icon")
g1secrole.place(x=116, y=45, width=30, height=30)

gr1icon = Label(member1, name="icon_label")
gr1icon.place(x=10, y=10, width=65, height=65)

gr1name = Label(
    member1,
    text="group1name",
    fg=dt.fg,
    bg=dt.bg_medium,
    font=("Inter SemiBold", 20 * -1), 
    name="name"
)
gr1name.place(x=80, y=5)
member1.place_forget()

member2 = Frame(
    window,
    width=230,
    height=85,
    bg=dt.bg_medium
)
member2.place(x=310, y=105)

member2.images = {"kick": kick_image, "lead": lead_image}

gr2kick = Button(
    member2,
    image=member2.images["kick"],
    borderwidth=0,
    highlightthickness=0,
    relief="flat",
    bg=dt.bg_medium,
    activebackground=dt.bg_medium, 
    name="kick"
)
gr2kick.place(x=189, y=45, width=30, height=30)

gr2lead = Button(
    member2,
    image=member2.images["lead"],
    borderwidth=0,
    highlightthickness=0,
    relief="flat",
    bg=dt.bg_medium,
    activebackground=dt.bg_medium, 
    name="promote"
)
gr2lead.place(x=153, y=45, width=30, height=30)

g2primrole = Label(member2, bg=dt.bg_medium, name="prim_icon")
g2primrole.place(x=81, y=45, width=30, height=30)

g2secrole = Label(member2, bg=dt.bg_medium, name="sec_icon")
g2secrole.place(x=116, y=45, width=30, height=30)

gr2icon = Label(member2, name="icon_label")
gr2icon.place(x=10, y=10, width=65, height=65)

gr2name = Label(
    member2,
    text="group2name",
    fg=dt.fg,
    bg=dt.bg_medium,
    font=("Inter SemiBold", 20 * -1), 
    name="name"
)
gr2name.place(x=80, y=5)
member2.place_forget()

member3 = Frame(
    window,
    width=230,
    height=85,
    bg=dt.bg_medium
)
member3.place(x=310, y=200)

member3.images = {"kick": kick_image, "lead": lead_image}

gr3kick = Button(
    member3,
    image=member3.images["kick"],
    borderwidth=0,
    highlightthickness=0,
    relief="flat",
    bg=dt.bg_medium,
    activebackground=dt.bg_medium, 
    name="kick"
)
gr3kick.place(x=189, y=45, width=30, height=30)

gr3lead = Button(
    member3,
    image=member3.images["lead"],
    borderwidth=0,
    highlightthickness=0,
    relief="flat",
    bg=dt.bg_medium,
    activebackground=dt.bg_medium, 
    name="promote"
)
gr3lead.place(x=153, y=45, width=30, height=30)

g3primrole = Label(member3, bg=dt.bg_medium, name="prim_icon")
g3primrole.place(x=81, y=45, width=30, height=30)

g3secrole = Label(member3, bg=dt.bg_medium, name="sec_icon")
g3secrole.place(x=116, y=45, width=30, height=30)

gr3icon = Label(member3, name="icon_label")
gr3icon.place(x=10, y=10, width=65, height=65)

gr3name = Label(
    member3,
    text="group3name",
    fg=dt.fg,
    bg=dt.bg_medium,
    font=("Inter SemiBold", 20 * -1), 
    name="name"
)
gr3name.place(x=80, y=5)
member3.place_forget()

member4 = Frame(
    window,
    width=230,
    height=85,
    bg=dt.bg_medium
)
member4.place(x=310, y=295)

member4.images = {"kick": kick_image, "lead": lead_image}

gr4kick = Button(
    member4,
    image=member4.images["kick"],
    borderwidth=0,
    highlightthickness=0,
    relief="flat",
    bg=dt.bg_medium,
    activebackground=dt.bg_medium, 
    name="kick"
)
gr4kick.place(x=189, y=45, width=30, height=30)

gr4lead = Button(
    member4,
    image=member4.images["lead"],
    borderwidth=0,
    highlightthickness=0,
    relief="flat",
    bg=dt.bg_medium,
    activebackground=dt.bg_medium, 
    name="promote"
)
gr4lead.place(x=153, y=45, width=30, height=30)

g4primrole = Label(member4, bg=dt.bg_medium, name="prim_icon")
g4primrole.place(x=81, y=45, width=30, height=30)

g4secrole = Label(member4, bg=dt.bg_medium, name="sec_icon")
g4secrole.place(x=116, y=45, width=30, height=30)

gr4icon = Label(member4, name="icon_label")
gr4icon.place(x=10, y=10, width=65, height=65)

gr4name = Label(
    member4,
    text="group4name",
    fg=dt.fg,
    bg=dt.bg_medium,
    font=("Inter SemiBold", 20 * -1), 
    name="name"
)
gr4name.place(x=80, y=5)
member4.place_forget()


game_button = Button(
    text="FIND MATCH",
    fg="white",
    font=("Inter SemiBold", 25 * -1),
    borderwidth=0,
    highlightthickness=0,
    command=lambda: cmnd.manageQueue(game_button, True, True),
    relief="flat",
    bg=dt.accent,
    activebackground=dt.accent_dark
)
game_button.place(
    x=130.0,
    y=307.0,
    width=160.0,
    height=65.0
)

canvas.create_rectangle(
    130.0,
    11.0,
    290.0,
    285.0,
    fill=dt.bg_medium,
    outline="")

prim_role = Button(
    borderwidth=0,
    highlightthickness=0,
    command=lambda: sendRoles(prim_role),
    name="prim",
    bg=dt.bg_dim,
    activebackground=dt.bg_dark
)
prim_role.place(
    x=155.0,
    y=225.0,
    width=50.0,
    height=50.0
)

sec_role = Button(
    borderwidth=0,
    highlightthickness=0,
    command=lambda: sendRoles(sec_role),
    name="sec",
    bg=dt.bg_dim,
    activebackground=dt.bg_dark
)
sec_role.place(
    x=225.0,
    y=225.0,
    width=50.0,
    height=50.0
)

iconimage = canvas.create_image(
    210.0,
    90.0,
)

nametext = canvas.create_text(
    210.0,
    165.0,
    anchor="center",
    text="NAMENAMENAME",
    fill=dt.fg,
    font=("Inter SemiBold", 20 * -1)
)

canvas.create_rectangle(
    0.0,
    0.0,
    111.0,
    400.0,
    fill=dt.bg_medium,
    outline="")

arena_button = Button(
    text="Arena",
    fg="white",
    font=("Inter SemiBold", 20 * -1),
    borderwidth=0,
    highlightthickness=0,
    command=lambda: sendLobby("arena"),
    relief="flat",
    bg=dt.bg_dark,
    activebackground=dt.bg_dim,
    activeforeground=dt.fg
)
arena_button.place(
    x=10.0,
    y=310.0,
    width=90.0,
    height=40.0
)

mayhem_button = Button(
    text="Mayhem",
    fg="white",
    font=("Inter SemiBold", 20 * -1),
    borderwidth=0,
    highlightthickness=0,
    command=lambda: sendLobby("mayhem"),
    relief="flat",
    bg=dt.bg_dark,
    activebackground=dt.bg_dim,
    activeforeground=dt.fg
)
mayhem_button.place(
    x=10.0,
    y=260.0,
    width=90.0,
    height=40.0
)

aram_button = Button(
    text="ARAM",
    fg="white",
    font=("Inter SemiBold", 20 * -1),
    borderwidth=0,
    highlightthickness=0,
    command=lambda: sendLobby("aram"),
    relief="flat",
    bg=dt.bg_dark,
    activebackground=dt.bg_dim,
    activeforeground=dt.fg
)
aram_button.place(
    x=10.0,
    y=210.0,
    width=90.0,
    height=40.0
)

flex_button = Button(
    text="Flex",
    fg="white",
    font=("Inter SemiBold", 20 * -1),
    borderwidth=0,
    highlightthickness=0,
    command=lambda: sendLobby("flex"),
    relief="flat",
    bg=dt.bg_dark,
    activebackground=dt.bg_dim,
    activeforeground=dt.fg
)
flex_button.place(
    x=10.0,
    y=160.0,
    width=90.0,
    height=40.0
)

soloq_button = Button(
    text="SoloQ",
    fg="white",
    font=("Inter SemiBold", 20 * -1),
    borderwidth=0,
    highlightthickness=0,
    command=lambda: sendLobby("soloq"),
    relief="flat",
    bg=dt.bg_dark,
    activebackground=dt.bg_dim,
    activeforeground=dt.fg
)
soloq_button.place(
    x=10.0,
    y=110.0,
    width=90.0,
    height=40.0
)

draft_button = Button(
    text="Draft",
    fg="white",
    font=("Inter SemiBold", 20 * -1),
    borderwidth=0,
    highlightthickness=0,
    command=lambda: sendLobby("draft"),
    relief="flat",
    bg=dt.bg_dark,
    activebackground=dt.bg_dim,
    activeforeground=dt.fg
)
draft_button.place(
    x=10.0,
    y=60.0,
    width=90.0,
    height=40.0
)

swiftplay_button = Button(
    text="Swift",
    fg="white",
    font=("Inter SemiBold", 20 * -1),
    borderwidth=0,
    highlightthickness=0,
    command=lambda: sendLobby("swiftplay"),
    relief="flat",
    bg=dt.bg_dark,
    activebackground=dt.bg_dim,
    activeforeground=dt.fg
)
swiftplay_button.place(
    x=10.0,
    y=10.0,
    width=90.0,
    height=40.0
)

button_frame = Frame(
    window,
    bg=dt.bg_dim
    )
button_frame.place(
    x=0,
    y=0,
    width=335,
    height=60
)  # adjust padding as needed

# List to store button references
role_buttons = []

role = ["TOP", "JUNGLE", "MIDDLE", "BOTTOM", "UTILITY", "FILL"]

# Create 6 buttons next to each other
for i in range(6):
    roleimage = PhotoImage( file=cmnd.relative_to_assets(f"roles\\{role[i]}.png") )
    currentrole = role[i]
    btn = Button(
        button_frame,
        width=50,
        height=50,
        image=roleimage,
        command=lambda r=currentrole: cmnd.postRole(button_frame, r),
        bg=dt.bg_dark,
        activebackground=dt.bg_dark,
        bd=0,
        highlightthickness=0,
        relief="flat"
    )
    btn.image = roleimage
    btn.pack(side="left", padx=(5, 0))
    role_buttons.append(btn)

button_frame.place_forget()

cmnd.getSummoner(canvas, nametext, iconimage)

def sendLobby(modeId):
    cmnd.setLobby(modeId, gamemode_buttons)

role_images = [prim_role, sec_role]
group_images = []

cmnd.saveRoles(role_images)
cmnd.showRoles()

def sendRoles(buttonId):
    cmnd.manageRoles(buttonId, button_frame, role_buttons)

member_frames = [member1, member2, member3, member4]
cmnd.setupFrames(member_frames)

gamemode_buttons = {"swiftplay":swiftplay_button, "draft":draft_button, "soloq":soloq_button, "flex":flex_button, "aram":aram_button, "mayhem":mayhem_button, "arena":arena_button}
window.resizable(False, False)
window.mainloop()